type PositionRecord {
  "Mode of the transport, either **bus**, **tram**, **metro** or **train**"
  mode: String!

  "The ID of next stop or station. Updated on each departure from or passing of a stop. EOL (end of line) after final stop and empty if the vehicle is leaving HSL area. Matches stop_id in GTFS (value of gtfsId field, without HSL: prefix, in Stop type in the routing API)."
  nextStop: String

  "ID that uniquely identifies the vehicle"
  id: String!

  "Route number visible to passengers."
  desi: String!
  "The line direction of the trip, either 1 or 2. \n Note: This does not exactly match direction_id in GTFS or the routing API. \n Value 1 here is same as 0 in GTFS and the Routing API. \n Value 2 here is same as 1 in GTFS and the Routing API."
  dir: String!
  "Unique ID of the operator running the trip (i.e. this value can be different than the operator ID in the topic, for example if the service has been subcontracted to another operator). The unique ID does not have prefix zeroes here."
  oper: Int!
  "Vehicle number that can be seen painted on the side of the vehicle, often next to the front door. Different operators may use overlapping vehicle numbers. Matches vehicle_number in the topic except without the prefix zeroes."
  veh: Int!
  "UTC timestamp with millisecond precision from the vehicle in ISO 8601 format (yyyy-MM-dd'T'HH:mm:ss.SSSZ)."
  tst: String!
  "Unix time in seconds from the vehicle."
  tsi: Int!
  "Speed of the vehicle, in meters per second (m/s)."
  spd: Float!
  "Heading of the vehicle, in degrees (⁰) starting clockwise from geographic north. Valid values are on the closed interval [0, 360]."
  hdg: Int!
  "WGS 84 latitude in degrees. null if location is unavailable."
  lat: Float
  "WGS 84 longitude in degrees. null if location is unavailable."
  long: Float
  "Acceleration (m/s^2), calculated from the speed on this and the previous message. Negative values indicate that the speed of the vehicle is decreasing."
  acc: Float!
  "Offset from the scheduled timetable in seconds (s). Negative values indicate lagging behind the schedule, positive values running ahead of schedule."
  dl: String!
  "The odometer reading in meters (m) since the start of the trip. Currently the values not very reliable."
  odo: Int!
  "Door status. 0 if all the doors are closed. 1 if any of the doors are open."
  drst: Int!
  "Operating day of the trip. The exact time when an operating day ends depends on the route. For most routes, the operating day ends at 4:30 AM on the next day. In that case, for example, the final moment of the operating day \"2018-04-05\" would be at 2018-04-06T04:30 local time."
  oday: String!
  "Internal journey descriptor, not meant to be useful for external use."
  jrn: Int!
  "Internal line descriptor, not meant to be useful for external use."
  line: Int!
  "Scheduled start time of the trip, i.e. the scheduled departure time from the first stop of the trip. The format follows HH:mm in 24-hour local time, not the 30-hour overlapping operating days present in GTFS. Matches start_time in the topic."
  start: String!
  "Location source, either **GPS**, **ODO**, **MAN** or **N/A**. **GPS** - location is received from GPS. **ODO** - location is calculated based on odometer value. **MAN** - location is specified manually **N/A** - location is unavailable"
  loc: String!
  "ID of the stop related to the event (the stop where the vehicle currently). null if the event is not related to any stop."
  stop: String
  "ID of the route the vehicle is currently running on"
  route: String!
  "Integer describing passenger occupancy level of the vehicle. Valid values are on interval [0, 100]. However, currently only values used are 0 (= vehicle has space and is accepting passengers) and 100 (= vehicle is full and might not accept passengers)"
  occu: Int!
}

type QueryType {
  a: String
}

type Subscription {
  transportEventsInArea(
    minLat: Float!
    maxLat: Float!
    minLon: Float!
    maxLon: Float!
  ): PositionRecord
}

type Query {
  a: String
}

schema {
  query: Query
  subscription: Subscription
}
